-d /Users/alexivanov/Desktop/UNI/FPGA/Lab 7/Lab 7/impl/gwsynthesis/Lab 7.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst /Users/alexivanov/Desktop/UNI/FPGA/Lab 7/Lab 7/src/Lab 7.cst
-cfg /Users/alexivanov/Desktop/UNI/FPGA/Lab 7/Lab 7/impl/pnr/device.cfg
-sdc /Users/alexivanov/Desktop/UNI/FPGA/Lab 7/Lab 7/src/Lab 7.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
